### PR TITLE
Debut blog with Kevin's post

### PR DESCRIPTION
**Pull request by dennisbrookner**
This PR adds Kevin's blog post on the folded-normal and Rice distributions. The post is still in progress.

### CODE REVIEW

**Comment by kmdalton** [comment]
Are we just waiting on review at this point?

**Comment by DHekstra** [comment]
I guess. I did not check the math, but otherwise this seems good to me.

**Comment by DHekstra** [comment]
as far as I am concerned, either of you can approve this too.

**Comment by dennisbrookner** [comment]
Great, I'll merge this in next time I'm on my computer!

**Pull request merged**
