### PR TITLE
Jekyll version of site

### PR DESCRIPTION
**Pull request by dennisbrookner**
A version of the site built with jekyll, which should be easier to maintain and update.

To-dos before this goes live:
- [ ] make a transparent version of the logo to go in the top left of the site
- [ ] update the filler text on the publications page as desired
- [ ] Include the bare minimum of contact information

### CODE REVIEW

**Comment by dennisbrookner** [comment]
It seems that on a pull request, github goes through and fully builds the website to make sure there are no errors, and then promptly throws that built preview version of the site in the trash can. In my limited digging around, people have been requestiing that github add a "preview site on pull request" feature for years, but they've yet to do it. Instead, there are some third-party tools like [this one](https://github.com/rossjrw/pr-preview-action) that provide that functionality, but I'm not sure if that's worth the set-up hassle. I can always just build/test things locally before pushing them. Thoughts?

**Comment by JBGreisman** [comment]
The checks provided at least let us know that the site will _build_. That's certainly a prerequisite...

I'm fine with needing to locally build the site to check out changes for now. I don't think it's worth the investment to change that at the moment, but we can revisit it if we find ourselves needing to update the site often.

**Comment by dennisbrookner** [comment]
Additionally, it probably makes sense to do local / offline work on a branch, so that changes always get pushed to the online version of that branch and then go through the PR build checks before going live

**Comment by JBGreisman** [comment]
yep agreed -- good policy in general, but definitely good practice in this case to avoid breaking the site. If we want to enforce this practice, we can add protections on the `main` branch, such as:

> _*Require a pull request before merging*_
> When enabled, all commits must be made to a non-protected branch and submitted via a pull request before they can be merged into a branch that matches this rule.

I think that's probably a good idea for this repo -- implicitly, anything coming through a PR will be checked. This will also prevent us from doing silly things like accidentally pushing to the `main` branch

**Comment by JBGreisman** [comment]
Cool -- I added the branch protection to `main`. This will also make it so that code review is required on any PRs merging into `main`.

**Review by JBGreisman — APPROVED** [review]
Looks good -- approving to see if status checks run after approval...

**Pull request merged**
